#!/bin/sh
# unset SESSION_MANAGER
# unset DBUS_SESSION_BUS_ADDRESS
# export XKL_XMODMAP_DISABLE=1
# export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
# export XDG_MENU_PREFIX="gnome-flashback-"

# [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
# [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# xsetroot -solid grey
# vncconfig -iconic &
#  dbus-launch --exit-with-session gnome-session &

 xrdb $HOME/.Xresources
startxfce4 &
